### PR TITLE
Various minor enhancements

### PR DESCRIPTION
**Pull request by yarikoptic**
I was just skimming through the code base and my editor was too much of a Christmas tree so I decided to act. Feel free to ignore.

### CODE REVIEW

**Comment by Ly0n** [comment]
It would be great to get feedback from you on the code base as it seems that you have been involved in a lot of open source Python projects.

**Comment by yarikoptic** [comment]
> It would be great to get feedback from you on the code base as it seems that you have been involved ...

it doesn't mean that my feedback would be "good".  One major aspect is that I "like" is CI testing and seems to be none here.

**Comment by Ly0n** [comment]
The only CI tests that we have are the Black Linter test and the Integration Tests. With every push we check if the new version is capable to still donate to the contributors of LibreSelery itself. Unit testing is already on the roadmap but since the codebase was changing and it is still experimental code that was shifted a little bit into the future.

**Comment by yarikoptic** [comment]
Well, I would've tried to compose some tests to simulate/check algorithm for allocation / distribution of funds under different settings/scenarios... I feel I keep getting too much for what I have contributed ;-)

**Comment by Ly0n** [comment]
The simulation is on the roadmap: https://github.com/protontypes/LibreSelery/issues/9
> I feel I keep getting too much for what I have contributed ;-)
Actually you are giving quite valuable feedback at this moment. :+1: 

The weights function will definitely be improved in the next weeks. Right now we developed the easy weights: Who is active in the last  X commits and who has done a minimum contribution to the project. Now we will get into the more complex stuff: https://github.com/protontypes/LibreSelery/issues/132
With every new weight that we calculate and add to the total weighs we hope to improve the distribution over time.

**Pull request merged**
