### PR TITLE
DOC: fixed up a phrase in README.md

### PR DESCRIPTION
**Pull request by yarikoptic**
Assuming that I fixed it correctly ;)

### CODE REVIEW

**Comment by Ly0n** [comment]
Well done! That's the whole idea. ;) Thanks for your contribution.  Could you please confirm that the payout worked correctly?

**Comment by yarikoptic** [comment]
confirming -- I am less poor now! ;)

**Comment by yarikoptic** [comment]
hm,  I got 3 more contributions to coinbase today although I did nothing useful: 2 tiny as before but also larger 0.00025 ... am I on the "payroll" now? ;)  I didn't want to open yet another issue to get even more less poor ;)

**Comment by Ly0n** [comment]
Yes that's the idea. Fresh Selery every day or maybe every month. We are investigating if it is better to payout monthly  than with every push. This would have multiple benefits like getting not so much email. The Github Action scheduler should be able to do that, but this will be part of another release. 

We reduced the payout since we had to test some issues in this part of the code. This why you got such a small amount. The experiment has not officially started yet and we still have to improve multiple parts of the project. Also the name will change to LibreSelery.

**Pull request merged**
